#!/bin/sh
set -eu

gh tailor \
  set-pack-meta \
  --name "ghas-trials/javascript-queries" \
  --version "0.0.0" \
  --default-suite "codeql-suites/javascript-code-scanning.qls" \
  stage

# inject query suites
cp suites/* stage/codeql-suites/

mkdir stage/tailor
cp Customizations.qll stage/tailor/

find 'stage/Security' -name '*.ql' -type f -print0 \
  | xargs -0 gh tailor ql-import -m "tailor.Customizations"
