#!/bin/sh
set -eu
cd -- "$(dirname -- "$0")"

rm -rf pack

gh tailor download --outdir pack "codeql/java-queries"

gh tailor \
  set-pack-meta \
  --name "ghas-trials/java-queries" \
  --version "0.0.0" \
  --default-suite "codeql-suites/java-code-scanning.qls" \
  pack

# Many customer state that XSS should have a higher severity
gh tailor \
  set-ql-meta \
  -m "security-severity" "9.0" \
  "pack/Security/CWE/CWE-079/XSS.ql"

# inject customizations
find pack/Security -name '*.ql' -type f -print0 \
  | xargs -0 gh tailor customize pack settings.yml

gh tailor create -i pack
