java.local_sources: "true"


# namespace; type; subtypes; name; signature; ext; output; kind
#java.sources:
  #- "javax.servlet;ServletRequest;false;getParameterMap;();;ReturnValue;remote"


# namespace; type; subtypes; name; signature; ext; input; kind
#java.sinks:
#  - "javax.net.ssl;HttpsURLConnection;true;setDefaultHostnameVerifier;;;Argument[0];set-hostname-verifier"


# namespace; type; subtypes; name; signature; ext; input; output; kind
java.summaries:
  - "java.lang;String;true;replace;;;Argument[-1];ReturnValue;taint;manual"
